### ISSUE TITLE
Will graphics passthrough work on a UEFI-booted host?

### ISSUE THREAD

**Issue by Menci** [yoonsikp/macOS-KVM-PCI-Passthrough#2]
I am running macOS on KVM on a UEFI-only machine. When I added graphics passthrough to the command line, it fails with:

```
qemu-system-x86_64: vfio-pci: Cannot read device rom at 0000:00:02.0
Device option ROM contents are probably invalid (check dmesg).
Skip option ROM probe with rombar=0, or load from file with romfile=
```

The error message in `dmesg`:

```
[ 1271.531853] vfio-pci 0000:00:02.0: enabling device (0400 -> 0403)
[ 1271.639246] vfio_ecap_init: 0000:00:02.0 hiding ecap 0x1b@0x100
[ 1272.865197] vfio-pci 0000:00:02.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
```

With `rombar=0` the VM boots but passthrough is NOT working. According to some guides, I tried to dump my graphics card's vBIOS ROM:

```
# cd /sys/bus/pci/devices/0000\:00\:02.0
# echo 1 > rom
# cat rom > /tmp/rom
cat: rom: Input/output error
```

`dmesg` gives me similar output. After searching these error messages, I found several examples that succeed dumping in legacy boot but failed in UEFI boot. But my laptop have only UEFI boot.

Did you succeed on graphics card passthrough with a legacy or a UEFI boot? Or can you try if it works on a UEFI boot?

**Comment by yoonsikp** [comment]
From what I believe, the passthrough process should work with both legacy and UEFI. The reason is the ROM is useful for when the system is booting, but should not make a difference once the system has booted. What graphics card are you using? And have you tried making a dump of the BIOS rom from windows?

**Comment by yoonsikp** [comment]
Also, you aren't removing the VNC display, correct? It is pretty useful as a debug tool, and might be required for macOS to boot up.

**Comment by Menci** [comment]
I can't dump my 520HD's ROM in Windows with GPU-Z either.

**Comment by yoonsikp** [comment]
Oh, you won't have much luck with Intel HD Graphics...

**Comment by Menci** [comment]
My laptop have both HD520 and 965M, but the display output is on HD520 and there's currently no NVIDIA WebDriver for macOS Mojave

**Comment by yoonsikp** [comment]
Unfortunately, there isn't much I can do to help fix this. Nvidia has really been uncooperative with Apple regarding this issue. Also, I am not sure how possible Intel HD Graphics passthrough is, but it's not something I can provide support with. Sorry about that!
